name: MinecraftIM
main: com.jascotty2.minecraftim.MinecraftIM
version: 0.2.6
author: jascotty2
website: https://github.com/jascotty2/Minecraft-IM
description: >
    Minecraft Messenger: for interacting with the server from an instant messenger
commands:
   minecraftim:
    description: General command for interacting with the minecraft IM
    usage: /<command>
    aliases: [mmess]